//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int Matin { get; set; }
        public string TenNLH { get; set; }
        public string SdtNLH { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayLH { get; set; }
    }
}
